# Generated by Django 5.0.6 on 2026-06-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='resolue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolue_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
