# Generated by Django 6.0.4 on 2026-05-13 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('orders', '0002_initial'),
        ('receptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receptionline',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.article'),
        ),
        migrations.AddField(
            model_name='receptionline',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.poline'),
        ),
        migrations.AddField(
            model_name='receptionline',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receptions.reception'),
        ),
    ]
