# Generated by Django 6.0.4 on 2026-05-13 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('APPROUVEE', 'Approuvée'), ('ENVOYEE', 'Envoyée'), ('PARTIELLEMENT_RECUE', 'Partiellement reçue'), ('RECUE', 'Reçue'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=25)),
                ('expected_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.article')),
            ],
        ),
    ]
