# Generated by Django 5.0.6 on 2026-06-20 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('DA', "Demande d'achat"), ('BC', 'Bon de commande'), ('RECEPTION', 'Réception'), ('FACTURE', 'Facture'), ('STOCK', 'Stock'), ('USER', 'Utilisateur')], max_length=15)),
                ('object_ref', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
