# Generated by Django 5.0.6 on 2026-06-16 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations_created', to=settings.AUTH_USER_MODEL)),
                ('demande_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='requests_app.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('INVITE', 'Invité'), ('PROPOSITION_RECUE', 'Proposition reçue'), ('RETENU', 'Retenu'), ('ELIMINE', 'Éliminé')], default='INVITE', max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='consultations.consultation')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_fournisseur', to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('consultation', 'fournisseur')},
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delai_livraison', models.PositiveIntegerField(help_text='Délai en jours')),
                ('commentaire', models.TextField(blank=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('retenue', models.BooleanField(default=False)),
                ('consultation_fournisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='consultations.consultationfournisseur')),
            ],
        ),
    ]
