# Generated by Django 5.0.6 on 2026-06-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='disponibilite',
            field=models.BooleanField(default=True, help_text='Article disponible immédiatement selon le fournisseur'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='qualite_estimee',
            field=models.PositiveSmallIntegerField(default=3, help_text='Note de qualité estimée de 1 (faible) à 5 (excellente)'),
        ),
    ]
