# Generated by Django 5.0.6 on 2026-06-16 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=10)),
                ('commentaire', models.TextField(blank=True)),
                ('ecart_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='orders.purchaseorder')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_created', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='factures.facture')),
            ],
        ),
    ]
